# Generated by Django 5.1.6 on 2025-07-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Izelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidad',
            options={},
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='duracion',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('cancelado', 'Cancelado')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='tipo_cita',
            field=models.CharField(choices=[('general', 'General'), ('especialista', 'Especialista'), ('virtual', 'Virtual')], default='general', max_length=50),
        ),
    ]
