# Generated by Django 4.2.6 on 2025-04-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Izelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaReferenciaCIE10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=5)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('habilitado', models.CharField(max_length=2)),
                ('extra_i_aplica_a_sexo', models.CharField(max_length=3)),
                ('extra_ii_edad_minima', models.CharField(max_length=3)),
                ('extra_iii_edad_maxima', models.CharField(max_length=3)),
                ('extra_iv_grupo_mortalidad', models.CharField(max_length=3)),
                ('extra_v', models.CharField(max_length=255)),
                ('extra_vi_capitulo', models.CharField(max_length=3)),
                ('extra_x', models.CharField(max_length=1)),
            ],
        ),
    ]
