# Generated by Django 5.1.6 on 2025-04-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Izelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('cancelado', 'Cancelado')], default='disponible', max_length=20),
        ),
    ]
