# Generated by Django 5.1.6 on 2025-06-20 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Izelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='numero_seguro_social',
        ),
    ]
