# Generated by Django 4.2.6 on 2025-03-20 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Izelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_agenda_cita', to='Izelapp.paciente'),
        ),
    ]
