# Generated by Django 4.2.6 on 2025-03-11 19:20

import Izelapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Izelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=Izelapp.models.user_directory_path, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_doc',
            field=models.CharField(choices=[('C.C', 'C.C'), ('T.I', 'T.I'), ('C.E', 'C.E')], max_length=20),
        ),
    ]
