# Generated by Django 5.1.6 on 2025-04-04 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Izelapp', '0002_disponibilidad_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='disponibilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asociadas', to='Izelapp.disponibilidad'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado_cita',
            field=models.CharField(choices=[('DP', 'Disponible'), ('agendada', 'Agendada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada'), ('NA', 'No atendida')], default='agendada', max_length=10),
        ),
    ]
