# Generated by Django 5.1.6 on 2025-06-21 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Izelapp', '0002_remove_paciente_numero_seguro_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='permisos',
        ),
    ]
