# Generated by Django 4.2.6 on 2025-04-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Izelapp', '0002_tablareferenciacie10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablareferenciacie10',
            name='extra_i_aplica_a_sexo',
            field=models.CharField(max_length=10),
        ),
    ]
