# Generated by Django 5.1.6 on 2025-04-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Izelapp', '0003_cita_disponibilidad_alter_cita_estado_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='centro_administracion',
            field=models.CharField(choices=[('Odontologia', 'Odontología'), ('Cirugia', 'Cirugía'), ('General', 'General'), ('Rayos_x', 'Rayos X')], max_length=255),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='permisos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(choices=[('Odontologia', 'Odontología'), ('Cirugia', 'Cirugía'), ('General', 'General'), ('Rayos_x', 'Rayos X')], max_length=100),
        ),
    ]
