# Generated by Django 4.2.6 on 2025-04-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Izelapp', '0003_alter_tablareferenciacie10_extra_i_aplica_a_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablareferenciacie10',
            name='extra_iv_grupo_mortalidad',
            field=models.CharField(max_length=10),
        ),
    ]
