# Generated by Django 5.1.6 on 2025-03-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Izelapp', '0004_alter_usuario_rh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='usuario',
        ),
    ]
