# Generated by Django 5.1.6 on 2025-03-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Izelapp', '0005_remove_administrador_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auxiliar',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='usuario',
        ),
    ]
