# Generated by Django 5.1.6 on 2025-03-26 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Izelapp', '0006_remove_auxiliar_usuario_remove_medico_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdeneMedica',
            new_name='OrdenMedica',
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_cita', models.CharField(choices=[('general', 'General'), ('odontologia', 'Odontología')], max_length=50)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Izelapp.medico')),
            ],
        ),
    ]
